name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create config.json
        run: |
          echo '${{ secrets.PROD_CONFIG_JSON }}' > ./career-hawk/src/config.json

      - name: Build Docker image
        run: |
          docker build -t jobfrontend ./career-hawk

      - name: Save image to archive
        run: |
          docker save jobfrontend | gzip > jobfrontend.tar.gz

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "jobfrontend.tar.gz"
          target: "/home/deploy/frontend/"

      - name: Load image and run on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy/frontend
            docker load < jobfrontend.tar.gz
            docker stop jobfrontend || true && docker rm jobfrontend || true
            docker run -d --name jobfrontend -p 80:80 jobfrontend